FROM node:20-alpine

WORKDIR /usr/src/app

# Build argument for DATABASE_URL
ARG DATABASE_URL

# Install pnpm globally
RUN npm install -g pnpm

# Copy source code
COPY . .

# Install dependencies
RUN pnpm install 

# Generate Prisma client
RUN pnpm run db:generate

# Set environment variable and build the web app specifically
ENV DATABASE_URL=${DATABASE_URL}
RUN pnpm run build --filter=web

EXPOSE 3000

CMD ["pnpm", "run", "start:web"]

