FROM node:20-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL

# Install pnpm globally
RUN npm install -g pnpm

# Copy source code
COPY . .

# Install dependencies
RUN pnpm install 

# Generate Prisma client
RUN pnpm run db:generate

# Build the web app specifically
RUN DATABASE_URL=${DATABASE_URL} pnpm run build --filter=web

EXPOSE 3000

CMD ["pnpm", "run", "start:web"]

