## Build the docker image for the backend service
## push the image to Docker Hub
## SSH into our VM and start new image

name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code # clone the repo
        uses: actions/checkout@v2

      - name: Docker login #login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image # build and push the docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: anjany06/http-server:${{ github.sha }} ## Every image have a unique version or the tag which is the commit sha(commit sha means the no display with every commit) here
